#!/bin/bash

echosts="ec2-54-210-1-206.compute-1.amazonaws.com
ec2-54-67-25-76.us-west-1.compute.amazonaws.com
ec2-35-161-203-105.us-west-2.compute.amazonaws.com
ec2-52-213-13-179.eu-west-1.compute.amazonaws.com
ec2-52-196-161-198.ap-northeast-1.compute.amazonaws.com
ec2-54-255-148-115.ap-southeast-1.compute.amazonaws.com
ec2-13-54-30-86.ap-southeast-2.compute.amazonaws.com
ec2-52-67-177-90.sa-east-1.compute.amazonaws.com
ec2-35-156-54-135.eu-central-1.compute.amazonaws.com"


if [ $# -lt 10 -o $# -gt 10 ]
then
    echo "\nUSAGE: ./runCDN -p <port> -o <origin> -n <name> -u <username> -i <keyfile>\n"
    exit 0
fi

port=$2
origin=$4
name=$6
username=$8
keyfile=${10}
dns_server="cs5700cdnproject.ccs.neu.edu"

for host in $echosts 
do
 	ssh -i $keyfile $username@$host "./httpserver -p $port -o $origin < /dev/null > std.out 2> std.err &"
	echo "Connection to $host started."
done

ssh -i $keyfile $username@$dns_server "./dnsserver -p $port -n $name < /dev/null > std.out 2> std.err &"
echo "Connection to $dns_server started."
